services: 
  mongodb:
    image: mongo:8.0.20
    restart: unless-stopped
    volumes:
      - ./.volumes/mongodb:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    image: ghcr.io/mariamair/myphysiotrainer:latest
    restart: on-failure
    env_file:
      - .env
    environment:
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      mongodb:
        condition: service_healthy


