services: 
  mongodb:
    image: mongo:8.0.20
    restart: unless-stopped
    volumes:
      - ./.volumes/mongodb:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    image: ghcr.io/mariamair/myphysiotrainer:latest
    restart: on-failure
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      BASE_URL: ${BASE_URL}
      API_URL: ${API_URL}
      SESSION_NAME: ${SESSION_NAME}
      SESSION_SECRET: ${SESSION_SECRET}
      LOG_LEVEL: ${LOG_LEVEL}
      LOGGER_COMBINED_LOG_FILE: ${LOGGER_COMBINED_LOG_FILE}
      LOGGER_ERROR_LOG_FILE: ${LOGGER_ERROR_LOG_FILE}
      LOGGER_UNCAUGHT_EXCEPTION_LOG_FILE: ${LOGGER_UNCAUGHT_EXCEPTION_LOG_FILE}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      mongodb:
        condition: service_healthy


